"""initial schema

Revision ID: 2d252d84ca45
Revises:
Create Date: 2026-09-27 17:47:37.674496
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2d252d84ca45"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book_clubs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_book_clubs_name"), "book_clubs", ["name"], unique=True)
    op.create_table(
        "books",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("open_library_key", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("author", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("isbn", sa.String(length=32), nullable=True),
        sa.Column("cover_image_url", sa.String(length=500), nullable=True),
        sa.Column("publication_year", sa.Integer(), nullable=True),
        sa.Column("genres", sa.JSON(), nullable=False),
        sa.Column("average_rating", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_books_open_library_key"), "books", ["open_library_key"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "book_club_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("club_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("OWNER", "ADMIN", "MODERATOR", "MEMBER", name="clubrole", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["club_id"], ["book_clubs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("club_id", "user_id", name="uq_club_member"),
    )
    op.create_index(
        op.f("ix_book_club_members_club_id"), "book_club_members", ["club_id"], unique=False
    )
    op.create_index(
        op.f("ix_book_club_members_user_id"), "book_club_members", ["user_id"], unique=False
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("club_id", sa.Integer(), nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["club_id"], ["book_clubs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sender_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_messages_club_id"), "chat_messages", ["club_id"], unique=False)
    op.create_index(
        op.f("ix_chat_messages_created_at"), "chat_messages", ["created_at"], unique=False
    )
    op.create_table(
        "club_books",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("club_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("CURRENT", "UPCOMING", "COMPLETED", name="clubbookstatus", native_enum=False),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["club_id"], ["book_clubs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("club_id", "book_id", name="uq_club_book"),
    )
    op.create_index(op.f("ix_club_books_book_id"), "club_books", ["book_id"], unique=False)
    op.create_index(op.f("ix_club_books_club_id"), "club_books", ["club_id"], unique=False)
    op.create_table(
        "discussion_threads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("club_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["club_id"], ["book_clubs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["creator_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_discussion_threads_book_id"), "discussion_threads", ["book_id"], unique=False
    )
    op.create_index(
        op.f("ix_discussion_threads_club_id"), "discussion_threads", ["club_id"], unique=False
    )
    op.create_table(
        "external_ratings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("external_user_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.CheckConstraint("rating >= 1 AND rating <= 5", name="ck_external_rating_1_5"),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "external_user_id", "book_id", name="uq_external_rating"),
    )
    op.create_index(
        op.f("ix_external_ratings_book_id"), "external_ratings", ["book_id"], unique=False
    )
    op.create_index(
        op.f("ix_external_ratings_external_user_id"),
        "external_ratings",
        ["external_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_ratings_source"), "external_ratings", ["source"], unique=False
    )
    op.create_table(
        "meetings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("club_id", sa.Integer(), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("location", sa.String(length=1000), nullable=True),
        sa.Column(
            "status",
            sa.Enum("SCHEDULED", "CANCELLED", name="meetingstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["club_id"], ["book_clubs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["creator_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_meetings_club_id"), "meetings", ["club_id"], unique=False)
    op.create_index(op.f("ix_meetings_end_time"), "meetings", ["end_time"], unique=False)
    op.create_index(op.f("ix_meetings_start_time"), "meetings", ["start_time"], unique=False)
    op.create_table(
        "user_availability",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_availability_end_time"), "user_availability", ["end_time"], unique=False
    )
    op.create_index(
        op.f("ix_user_availability_start_time"), "user_availability", ["start_time"], unique=False
    )
    op.create_index(
        op.f("ix_user_availability_user_id"), "user_availability", ["user_id"], unique=False
    )
    op.create_table(
        "user_books",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("WANT_TO_READ", "READING", "READ", name="readingstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("review", sa.Text(), nullable=True),
        sa.CheckConstraint("rating IS NULL OR (rating >= 1 AND rating <= 5)", name="ck_rating_1_5"),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "book_id", name="uq_user_book"),
    )
    op.create_index(op.f("ix_user_books_book_id"), "user_books", ["book_id"], unique=False)
    op.create_index(op.f("ix_user_books_user_id"), "user_books", ["user_id"], unique=False)
    op.create_table(
        "user_genres",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("genre", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "genre", name="uq_user_genre"),
    )
    op.create_index(op.f("ix_user_genres_user_id"), "user_genres", ["user_id"], unique=False)
    op.create_table(
        "weekly_availability",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("start_minute", sa.Integer(), nullable=False),
        sa.Column("end_minute", sa.Integer(), nullable=False),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_weekly_availability_user_id"), "weekly_availability", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_weekly_availability_weekday"), "weekly_availability", ["weekday"], unique=False
    )
    op.create_table(
        "discussion_posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("thread_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["discussion_posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["thread_id"], ["discussion_threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_discussion_posts_parent_id"), "discussion_posts", ["parent_id"], unique=False
    )
    op.create_index(
        op.f("ix_discussion_posts_thread_id"), "discussion_posts", ["thread_id"], unique=False
    )
    op.create_table(
        "meeting_attendees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ACCEPTED",
                "GOING",
                "MAYBE",
                "DECLINED",
                name="rsvpstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["meeting_id"], ["meetings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("meeting_id", "user_id", name="uq_meeting_attendee"),
    )
    op.create_index(
        op.f("ix_meeting_attendees_meeting_id"), "meeting_attendees", ["meeting_id"], unique=False
    )
    op.create_index(
        op.f("ix_meeting_attendees_user_id"), "meeting_attendees", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_meeting_attendees_user_id"), table_name="meeting_attendees")
    op.drop_index(op.f("ix_meeting_attendees_meeting_id"), table_name="meeting_attendees")
    op.drop_table("meeting_attendees")
    op.drop_index(op.f("ix_discussion_posts_thread_id"), table_name="discussion_posts")
    op.drop_index(op.f("ix_discussion_posts_parent_id"), table_name="discussion_posts")
    op.drop_table("discussion_posts")
    op.drop_index(op.f("ix_weekly_availability_weekday"), table_name="weekly_availability")
    op.drop_index(op.f("ix_weekly_availability_user_id"), table_name="weekly_availability")
    op.drop_table("weekly_availability")
    op.drop_index(op.f("ix_user_genres_user_id"), table_name="user_genres")
    op.drop_table("user_genres")
    op.drop_index(op.f("ix_user_books_user_id"), table_name="user_books")
    op.drop_index(op.f("ix_user_books_book_id"), table_name="user_books")
    op.drop_table("user_books")
    op.drop_index(op.f("ix_user_availability_user_id"), table_name="user_availability")
    op.drop_index(op.f("ix_user_availability_start_time"), table_name="user_availability")
    op.drop_index(op.f("ix_user_availability_end_time"), table_name="user_availability")
    op.drop_table("user_availability")
    op.drop_index(op.f("ix_meetings_start_time"), table_name="meetings")
    op.drop_index(op.f("ix_meetings_end_time"), table_name="meetings")
    op.drop_index(op.f("ix_meetings_club_id"), table_name="meetings")
    op.drop_table("meetings")
    op.drop_index(op.f("ix_external_ratings_source"), table_name="external_ratings")
    op.drop_index(op.f("ix_external_ratings_external_user_id"), table_name="external_ratings")
    op.drop_index(op.f("ix_external_ratings_book_id"), table_name="external_ratings")
    op.drop_table("external_ratings")
    op.drop_index(op.f("ix_discussion_threads_club_id"), table_name="discussion_threads")
    op.drop_index(op.f("ix_discussion_threads_book_id"), table_name="discussion_threads")
    op.drop_table("discussion_threads")
    op.drop_index(op.f("ix_club_books_club_id"), table_name="club_books")
    op.drop_index(op.f("ix_club_books_book_id"), table_name="club_books")
    op.drop_table("club_books")
    op.drop_index(op.f("ix_chat_messages_created_at"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_club_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_book_club_members_user_id"), table_name="book_club_members")
    op.drop_index(op.f("ix_book_club_members_club_id"), table_name="book_club_members")
    op.drop_table("book_club_members")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_books_open_library_key"), table_name="books")
    op.drop_table("books")
    op.drop_index(op.f("ix_book_clubs_name"), table_name="book_clubs")
    op.drop_table("book_clubs")
    # ### end Alembic commands ###
