"""add age to users

Revision ID: fc25c59d3ede
Revises: 2d252d84ca45
Create Date: 2026-09-27 17:47:57.495601
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'fc25c59d3ede'
down_revision: str | None = '2d252d84ca45'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    # ### end Alembic commands ###